# LOCALHOST

### Get all World Cup Champions
GET http://localhost:3000/worldCupChampions

### Get World Cup Champion by _id
GET http://localhost:3000/worldCupChampions/

### Create new World Cup Champion
POST http://localhost:3000/worldCupChampions
Content-Type: application/json

{
  "name": "USA",
  "continent": "North America",
  "winCount": 0
}

### Update World Cup Champion
PUT http://localhost:3000/worldCupChampions/
Content-Type: application/json

{
  "name": "Mexico",
  "continent": "Central America",
  "winCount": 0
}

### Delete World Cup Champion
DELETE http://localhost:3000/worldCupChampions/


# PRODUCTION - RENDER

### Get all World Cup Champions
GET https://cse-341-proj-2.onrender.com/worldCupChampions

### Get World Cup Champion by _id
GET https://cse-341-proj-2.onrender.com/worldCupChampions/

### Create new World Cup Champion
POST https://cse-341-proj-2.onrender.com/worldCupChampions
Content-Type: application/json

{
  "name": "Brazil",
  "continent": "South America",
  "winCount": 4
}

### Update World Cup Champion
PUT https://cse-341-proj-2.onrender.com/worldCupChampions/
Content-Type: application/json

{
  "name": "Brazil",
  "continent": "South America",
  "winCount": 5
}

### Delete World Cup Champion
DELETE https://cse-341-proj-2.onrender.com/worldCupChampions/